### ISSUE TITLE
Add tasks description and information about the project

### ISSUE THREAD

**Issue by M1-Elmasry** [Davenchy/alx-files_manager#35]
## Suggestion
I suggest adding detailed descriptions of the project's tasks provided by ALX, either in a separate Markdown file or within the existing `README.md`. I see this addition will enhance the clarity of the tasks completed within this repository, helps viewers in understanding the purpose and scope of each task and recognizing the contributions of team members more clearly.

### Table of Contents
- [Task 1: Name (Contributor Name)](#task-1)
- [Task 2: Name (Contributor Name)](#task-2)
- [Task 3: Name (Contributor Name)](#task-3)

### Task 1: Name (Contributor Name)
Detailed description of Task 1 provided by ALX.

### Task 2: Name (Contributor Name)
Detailed description of Task 2 provided by ALX.

### Task 3: Name (Contributor Name)
Detailed description of Task 3 provided by ALX.

**Comment by Davenchy** [comment]
I completely agree with your suggestion. Additionally, we could reference the issues and To-Do list for each task or feature. Let's focus on completing the mandatory tasks first to save time. After that, we can update the README.md file, as it currently contains incorrect details about our project and file structure. Depending on the size of the updated README, we can decide whether to include the task descriptions in the same file or in a new Markdown file.

- [ ] Complete mandatory tasks
- [ ] Update README file
- [ ] Add tasks detailed descriptions

**Comment by Davenchy** [comment]
We have to update the README file too.
- Add a link to the task details file.
- Update the README file to fill the template with our project details.
